[versions]
mockK = "1.14.5"

[libraries]
mockK = { module = "io.mockk:mockk", version.ref = "mockK" }

spring-quartz = { module = "org.springframework.boot:spring-boot-starter-quartz" }
spring-tx = { module = "org.springframework:spring-tx" }
